# Generated by Django 4.1.7 on 2023-04-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='fest',
            field=models.CharField(choices=[('syntaxia', 'SYNTAXIA'), ('multiplexer', 'MULTIPLEXER'), ('gaming', 'GAMING')], default=None, max_length=15),
        ),
    ]
